import cv2 as cv
import numpy as np
from segment_anything import sam_model_registry, SamPredictor


def sam_loader(checkpoint: str, model_type: str, device: str) -> SamPredictor:
    """ 
    Load a chosen SAM to GPU.
    
    Parameters
    ----------
    checkpoint : 'str'
        path to the SAM model
    model_type : 'str'
        SAM model type
    device : 'str'
        cpu vs. cuda
            
    Returns
    -------
    sampler : obj : 'SamPredictor'
        SAM loaded in the device
    """
    sam = sam_model_registry[model_type](checkpoint=checkpoint)
    sam.to(device=device)

    mask_predictor = SamPredictor(sam_model=sam)

    return mask_predictor


def segmentation_visualizer(dst: np.array, masks: np.array, blend: float = 0.5) -> np.array:
    """ 
    Visualize masks generated by SAM.
    
    Parameters
    ----------
    dst : obj : 'np.array'
        original image file we choose to process using SAM
    masks : obj : `np.array` 
        boolean mask geneerated SAM
    blend : float 
        paramtere that controlls transparency of the mask
        
    Returns
    -------
    result : obj : 'np.array'
        final image with a mask
    """
    cyan = np.full_like(dst,(255,255,0))
    img_cyan = cv.addWeighted(dst, blend, cyan, 1-blend, 0)

    c,h,w = masks.shape
    masks = 255 * masks.astype(np.uint8).reshape(h,w,c)
    result = np.where(masks==255, img_cyan, dst)

    cv.imshow('result', result)
    cv.waitKey(0)
    cv.destroyAllWindows()   

    return result
